### ISSUE TITLE
Dockerize project

### ISSUE THREAD

**Issue by mkogerd** [mkogerd/macro-tracker#2]
# Context
This project consists of a web client, backend server, and a SQL database. These take effort to setup across different environments. Much of this effort could be alleviated by dockerizing the project components, allowing each part to be spun up with a single command.

# AC
* A dockerfile is created for running the web client
* A dockerfile is created for running the backend server
* A dockerfile is created for running the database, initialized with the expected schema

**Comment by nkilm** [comment]
@mkogerd I want to work on this issue, but I'll need some help as I'm still learning Docker.

**Comment by mkogerd** [comment]
Hey @nkilm! 

I already had some of this work in-progress so I went ahead and completed this task, but thanks for the offer. If you're curious about how it was done (for educational purposes), feel free to take a look at PR #8! I added a bunch of context in the PR description, and additionally there is info on how to use the added docker functionality in the added READMEs.

**Comment by nkilm** [comment]
@mkogerd No problem! Looks gr8 by the way.

Also you missed one word here I think, 

https://github.com/mkogerd/macro-tracker/blame/master/client/README.md#L16

**Comment by mkogerd** [comment]
Oh you're right, thanks for pointing that out

**Comment by nkilm** [comment]
@mkogerd Happy to help!
